import { z } from "zod";

export const onboardingAnswersSchema = z.object({
  accountName: z.string().trim().min(1, "계정 이름을 입력해주세요").max(80),
  instagramHandle: z
    .string()
    .trim()
    .min(1, "Instagram ID를 입력해주세요")
    .max(30)
    .regex(/^[A-Za-z0-9._]+$/, "Instagram ID는 영문, 숫자, 마침표, 밑줄만 사용할 수 있어요"),
  desiredMood: z.string().trim().min(1, "원하는 분위기를 입력해주세요").max(500),
  mainTopics: z.string().trim().min(1, "주로 다룰 주제를 입력해주세요").max(500),
  preferredFormats: z.string().trim().min(1, "유지하고 싶은 형식을 입력해주세요").max(500),
});

/**
 * Structured output generated by the onboarding model. Account identifiers
 * stay outside this schema so the model cannot rewrite user-owned identity.
 */
export const generatedBrandProfileSchema = z.object({
  brandSummary: z.string(),
  moodKeywords: z.array(z.string()).min(2).max(6),
  contentPillars: z.array(z.string()).min(1).max(6),
  formatPreferences: z.array(z.string()).min(1).max(6),
  voiceGuidelines: z.array(z.string()).min(2).max(6),
  visualGuidelines: z.array(z.string()).min(2).max(6),
  marketerInstructions: z.array(z.string()).min(2).max(6),
  editorInstructions: z.array(z.string()).min(2).max(6),
  keepRules: z.array(z.string()).min(1).max(6),
  avoidRules: z.array(z.string()).min(1).max(6),
});

export const brandContextSchema = generatedBrandProfileSchema.extend({
  schemaVersion: z.literal("1.0"),
  accountName: z.string(),
  instagramHandle: z.string(),
  generatedAt: z.string(),
});

export const storedOnboardingProfileSchema = z.object({
  answers: onboardingAnswersSchema,
  context: brandContextSchema,
  updatedAt: z.string(),
});

export type OnboardingAnswers = z.infer<typeof onboardingAnswersSchema>;
export type GeneratedBrandProfile = z.infer<typeof generatedBrandProfileSchema>;
export type BrandContext = z.infer<typeof brandContextSchema>;
export type StoredOnboardingProfile = z.infer<typeof storedOnboardingProfileSchema>;

export const EMPTY_ONBOARDING_ANSWERS: OnboardingAnswers = {
  accountName: "",
  instagramHandle: "",
  desiredMood: "",
  mainTopics: "",
  preferredFormats: "",
};

export function normalizeInstagramHandle(value: string): string {
  const trimmed = value.trim();
  const fromUrl = trimmed.match(/instagram\.com\/([^/?#]+)/i)?.[1];
  return (fromUrl ?? trimmed).replace(/^@+/, "").replace(/\/+$/, "");
}

export function brandContextToAgentText(context: BrandContext | null): string {
  if (!context) return "";

  return [
    `Account: ${context.accountName} (@${context.instagramHandle})`,
    `Brand summary: ${context.brandSummary}`,
    `Mood: ${context.moodKeywords.join(", ")}`,
    `Content pillars: ${context.contentPillars.join(", ")}`,
    `Preferred formats: ${context.formatPreferences.join(", ")}`,
    `Voice: ${context.voiceGuidelines.join(" / ")}`,
    `Visual direction: ${context.visualGuidelines.join(" / ")}`,
    `Keep: ${context.keepRules.join(" / ")}`,
    `Avoid: ${context.avoidRules.join(" / ")}`,
  ].join("\n");
}
